# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a153b0256697c839d0a242f79bfeeaf328aa570101f0c9045ec95b94b7f83b9d54704e1f484dbc83b8b2afb06caa00c37f754cdb9e761daa706b1285dc4b9efd

test:
  secret_key_base: 3fbcea05b4331d458fbec7e4b4bd5ff84c0b08954e197f3969c77084260159ac5981812a818e66230d02ba621a35e939fb9a2a229b0f384c5f1dd326821b48a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
